# Input variables. Every one carries a default so `terraform validate` runs with
# no input file, no credentials and no backend.

variable "project_name" {
  description = "Name prefix applied to every resource and to the default tag set."
  type        = string
  default     = "tasklane"
}

variable "aws_region" {
  description = "Region hosting the network, database and object storage."
  type        = string
  default     = "eu-west-1"
}

variable "vpc_cidr" {
  description = "IPv4 CIDR block for the VPC."
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for the public subnets, one per availability zone. These hold the load balancer only; nothing else is reachable from the internet."
  type        = list(string)
  default     = ["10.0.0.0/20", "10.0.16.0/20"]
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for the private subnets, one per availability zone. These hold the application tasks and the database, and have no route to an internet gateway."
  type        = list(string)
  default     = ["10.0.128.0/20", "10.0.144.0/20"]
}

variable "database_name" {
  description = "Name of the initial Postgres database."
  type        = string
  default     = "tasklane"
}

variable "database_username" {
  description = "Master username for the Postgres instance. The matching password is generated by RDS into Secrets Manager and never appears in this module."
  type        = string
  default     = "tasklane_admin"
}

variable "database_engine_version" {
  description = "Postgres major version. Minor versions are applied automatically rather than pinned, so published patches are not deferred to a code change."
  type        = string
  default     = "16"
}

variable "database_instance_class" {
  description = "Instance class for the Postgres instance."
  type        = string
  default     = "db.t4g.micro"
}

variable "log_retention_days" {
  description = "Retention period for VPC flow logs and database logs in CloudWatch Logs."
  type        = number
  default     = 365
}
